// <auto-generated />
using System;
using ESP32Monitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESP32Monitor.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

        modelBuilder.Entity("ESP32Monitor.Models.ParameterLog", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("NewValue")
                .HasColumnType("TEXT");

            b.Property<string>("OldValue")
                .HasColumnType("TEXT");

            b.Property<string>("ParameterName")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<string>("Source")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("TEXT");

            b.Property<DateTime>("Timestamp")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("Timestamp");

            b.ToTable("ParameterLogs");
        });
#pragma warning restore 612, 618
    }
}
